apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: awx
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: awx
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awx
  namespace: awx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount }}
  namespace: {{ .Values.namespace }}
